version: "3"

networks:
  stack_ponte:
    external: true

services:
  frontend_alvitre:
    container_name: "alvitre"
    image: webdevops/apache
    working_dir: /app
    volumes:
      - "${PATHPESSOAL}/alvitre-site/front/dist:/app"
    networks:
      - stack_ponte
    ports:
      - "3100:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sitealvitre.rule=Host(`www.${DOMAIN}`,`${DOMAIN}`)"
      - traefik.http.services.sitealvitre.loadbalancer.server.port=80
      - "traefik.http.routers.sitealvitre.tls.certresolver=le"
